# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq6-oKE3mB-DBenrC9xj6pGd7Mub1PRn
"""

import streamlit as st
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv("ineq_data.csv")

# Fit regression
reg_data = df[["Gini coefficient", "log_gdp_pc", "cons_pct_gdp"]].dropna()
X = reg_data[["log_gdp_pc", "cons_pct_gdp"]]
X = sm.add_constant(X)
y = reg_data["Gini coefficient"]
model = sm.OLS(y, X).fit()

st.title("Inequality, Growth and Consumption")

st.write(
    "This app uses a simple regression model to explore how income "
    "levels and final consumption expenditure (% of GDP) relate to "
    "the Gini coefficient for a small set of countries."
)

st.sidebar.header("Choose parameters")

log_gdp = st.sidebar.slider(
    "log(GDP per capita)",
    float(df["log_gdp_pc"].min()),
    float(df["log_gdp_pc"].max()),
    float(df["log_gdp_pc"].mean())
)

cons = st.sidebar.slider(
    "Final consumption expenditure (% of GDP)",
    float(df["cons_pct_gdp"].min()),
    float(df["cons_pct_gdp"].max()),
    float(df["cons_pct_gdp"].mean())
)

X_new = pd.DataFrame({
    "const": [1.0],
    "log_gdp_pc": [log_gdp],
    "cons_pct_gdp": [cons]
})
predicted_gini = model.predict(X_new)[0]

st.subheader("Predicted inequality for chosen values")
st.write(f"**Predicted Gini coefficient:** {predicted_gini:.3f}")

st.subheader("Observed data and your chosen point")

fig, ax = plt.subplots(figsize=(6, 4))
ax.scatter(df["log_gdp_pc"], df["Gini coefficient"], alpha=0.4, label="Observed")
ax.scatter([log_gdp], [predicted_gini], color="red", label="Your choice")
ax.set_xlabel("log(GDP per capita)")
ax.set_ylabel("Gini coefficient")
ax.legend()
st.pyplot(fig)