# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq6-oKE3mB-DBenrC9xj6pGd7Mub1PRn
"""

import streamlit as st
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv("ineq_data.csv")

# Select data
all_countries = sorted(df["Entity"].unique())

selected_countries = st.sidebar.multiselect(
    "Countries to display",
    options=all_countries,
    default=all_countries  # or a subset if you prefer
)

# Filter data
if selected_countries:
    df_view = df[df["Entity"].isin(selected_countries)]
else:
    df_view = df.copy()

# Fit regression
reg_data = df[["Gini coefficient", "log_gdp_pc", "cons_pct_gdp"]].dropna()
X = reg_data[["log_gdp_pc", "cons_pct_gdp"]]
X = sm.add_constant(X)
y = reg_data["Gini coefficient"]
model = sm.OLS(y, X).fit()

st.title("Inequality, Growth and Consumption")

st.write(
    "This app uses a simple regression model to explore how income "
    "levels and final consumption expenditure (% of GDP) relate to "
    "the Gini coefficient for a small set of countries."
)

st.sidebar.header("Choose parameters")

log_gdp = st.sidebar.slider(
    "log(GDP per capita)",
    float(df["log_gdp_pc"].min()),
    float(df["log_gdp_pc"].max()),
    float(df["log_gdp_pc"].mean())
)

cons = st.sidebar.slider(
    "Final consumption expenditure (% of GDP)",
    float(df["cons_pct_gdp"].min()),
    float(df["cons_pct_gdp"].max()),
    float(df["cons_pct_gdp"].mean())
)

X_new = pd.DataFrame({
    "const": [1.0],
    "log_gdp_pc": [log_gdp],
    "cons_pct_gdp": [cons]
})
predicted_gini = model.predict(X_new)[0]

# Plotting
st.subheader("Observed data for selected countries")

fig, ax = plt.subplots(figsize=(6, 4))

for c in selected_countries:
    subset = df_view[df_view["Entity"] == c]
    ax.scatter(
        subset["log_gdp_pc"],
        subset["Gini coefficient"],
        alpha=0.6,
        label=c
    )

# Highlight chosen point (still based on sliders)
ax.scatter(
    [log_gdp],
    [predicted_gini],
    color="red",
    edgecolor="black",
    label="Your choice"
)

ax.set_xlabel("log(GDP per capita)")
ax.set_ylabel("Gini coefficient")
ax.legend()
st.pyplot(fig)

# Description
st.subheader("Summary statistics for selected countries")

summary = (
    df_view[["Entity", "Gini coefficient", "GDP per capita", "cons_pct_gdp"]]
    .groupby("Entity")
    .agg({
        "Gini coefficient": "mean",
        "GDP per capita": "mean",
        "cons_pct_gdp": "mean",
    })
    .rename(columns={
        "Gini coefficient": "Mean Gini",
        "GDP per capita": "Mean GDP pc",
        "cons_pct_gdp": "Mean cons % GDP",
    })
    .round(3)
)

st.dataframe(summary)

# Consumption VS Gini
st.subheader("Consumption share vs inequality")

fig2, ax2 = plt.subplots(figsize=(6, 4))

for c in selected_countries:
    subset = df_view[df_view["Entity"] == c]
    ax2.scatter(
        subset["cons_pct_gdp"],
        subset["Gini coefficient"],
        alpha=0.6,
        label=c
    )

ax2.set_xlabel("Final consumption expenditure (% of GDP)")
ax2.set_ylabel("Gini coefficient")
ax2.legend()
st.pyplot(fig2)
